Repository pisa-engine/pisa, pull requests merged in 2019-01, with the labels that each got.

#39 Replaced progress logger with progress bar
  include/binary_freq_collection.hpp
  include/util/index_build_utils.hpp
  src/create_freq_index.cpp
  src/optimal_hybrid_index.cpp
  src/profile_queries.cpp
  src/queries.cpp
  src/shuffle_docids.cpp
Labels: enhancement

#25 Support thresholds for query performance/correctness tests
  src/CMakeLists.txt
  src/queries.cpp
  src/thresholds.cpp
  test/test_data/top5_thresholds
  test/test_ranked_queries.cpp
Labels: wip

#70 Support parallel tests by using generated temp directories
  test/temporary_directory.hpp
  test/test_block_freq_index.cpp
  test/test_sample_index.cpp
  test/test_sequence_collection.cpp
Labels: CI

#69 Expose Catch2 test cases to ctest
  .travis.yml
  CMakeLists.txt
  test/CMakeLists.txt
Labels: CI, wip

#19 Create Index_Compression.md
  docs/Compression_Algorithms.md
Labels: documentation, wip
