Repository pisa-engine/pisa, pull requests merged in 2019-04, with the labels that each got.

#141 Network BP
  include/pisa/recursive_graph_bisection.hpp
  script/bp/generate_config_net.py
  script/bp/validate.py
  src/recursive_graph_bisection.cpp
Labels: enhancement

#149 Add heap score check to accumulation of top-k heap
  include/pisa/accumulator/lazy_accumulator.hpp
  include/pisa/accumulator/simple_accumulator.hpp
Labels: discussion, performance

#154 Stopwords
  include/pisa/query/queries.hpp
  src/compute_intersection.cpp
  src/evaluate_queries.cpp
  src/queries.cpp
  src/thresholds.cpp
Labels: enhancement

#166 Fix query lowercase
  include/pisa/query/queries.hpp
  src/parse_collection.cpp
Labels: bug

#173 Insert document ID in MaxScore, BMM and ranked_or_taat
  include/pisa/accumulator/simple_accumulator.hpp
  include/pisa/query/algorithm/block_max_maxscore_query.hpp
  include/pisa/query/algorithm/maxscore_query.hpp
Labels: bug

#174 Fix log message
  include/pisa/query/queries.hpp
Labels: bug

#140 Implement payload vector
  docs/source/evaluate_precision.md
  docs/source/query_index.md
  include/pisa/forward_index_builder.hpp
  include/pisa/io.hpp
  include/pisa/payload_vector.hpp
  include/pisa/query/queries.hpp
  src/CMakeLists.txt
  src/evaluate_queries.cpp
  src/lexicon.cpp
  src/queries.cpp
  test/test_forward_index_builder.cpp
  test/test_payload_vector.cpp
Labels: enhancement

#178 Implement tokenizer and use for query parsing.
  include/pisa/forward_index_builder.hpp
  include/pisa/query/queries.hpp
  include/pisa/tokenizer.hpp
  test/test_tokenizer.cpp
Labels: enhancement

#171 Update default params for bmw25
  include/pisa/scorer/bm25.hpp
Labels: enhancement

#181 Parallel evaluate
  src/evaluate_queries.cpp
Labels: enhancement

#182 Add weights to query terms
  include/pisa/cursor/block_max_scored_cursor.hpp
  include/pisa/cursor/cursor.hpp
  include/pisa/cursor/max_scored_cursor.hpp
  include/pisa/cursor/scored_cursor.hpp
  include/pisa/query/queries.hpp
  src/compute_intersection.cpp
  src/evaluate_queries.cpp
  src/profile_queries.cpp
  src/queries.cpp
  src/thresholds.cpp
  test/test_bmw_queries.cpp
  test/test_ranked_queries.cpp
Labels: enhancement, refactoring
