Repository pisa-engine/pisa, pull requests merged in 2019-05, with the labels that each got.

#187 Block params
  docs/source/query_index.md
  include/pisa/wand_data.hpp
  include/pisa/wand_data_compressed.hpp
  include/pisa/wand_data_range.hpp
  include/pisa/wand_data_raw.hpp
  include/pisa/wand_utils.hpp
  src/create_wand_data.cpp
  test/test_bmw_queries.cpp
  test/test_ranked_queries.cpp
  test/test_wand_data.cpp
Labels: documentation, enhancement

#106 Sharding forward index
  .clang-format
  docs/source/sharding.md
  include/pisa/forward_index_builder.hpp
  include/pisa/invert.hpp
  include/pisa/io.hpp
  include/pisa/sharding.hpp
  include/pisa/type_safe.hpp
  include/pisa/vec_map.hpp
  script/compress-shards.sh
  script/invert-shards.sh
  src/CMakeLists.txt
  src/partition_fwd_index.cpp
  test/temporary_directory.hpp
  test/test_partition_fwd_index.cpp
Labels: enhancement

#195 Fix logger names
  src/queries.cpp
Labels: bug
